### ISSUE TITLE
Adding the VF-1R to Valkyrie Squadron

### ISSUE THREAD

**Issue by devillin-one** [BSData/robotech-rpg-tactics#11]
Whenever I try to use the VF-1R fighter selection, I'm getting an error of:

Valky Squadron has 4 too many selections of VF-1R Flight LEader )maximum -3)
set max selections to 0
increment maxselections by 2 (repeating)
decrement maxselections by 1(repeating)

**Comment by efalsken** [comment]
The current version of Battlescribe has some limitations, but there is a major release coming that will make this easier. Before selecting any VF-1Rs in the Valkyrie Squadron Core, you must add a "VF-1R Upgrade" card in the Support Cards section. This will increase the limit of the VF-1Rs and will require you to manually remove two of your VF-1A or VF-1J squadron members. You can upgrade two squadron members, or the squadron leader and one member.
